apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-juridisk-vurdering-test-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  resources:
    limits:
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 400Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: juridisk-vurdering-db
  kafka:
    pool: {{kafkaPool}}
