server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://${NAIS_DATABASE_FLEX_JURIDISK_VURDERING_TEST_BACKEND_JURIDISK_VURDERING_DB_HOST}:${NAIS_DATABASE_FLEX_JURIDISK_VURDERING_TEST_BACKEND_JURIDISK_VURDERING_DB_PORT}/${NAIS_DATABASE_FLEX_JURIDISK_VURDERING_TEST_BACKEND_JURIDISK_VURDERING_DB_DATABASE}?reWriteBatchedInserts=true"
    username: ${NAIS_DATABASE_FLEX_JURIDISK_VURDERING_TEST_BACKEND_JURIDISK_VURDERING_DB_USERNAME}
    password: ${NAIS_DATABASE_FLEX_JURIDISK_VURDERING_TEST_BACKEND_JURIDISK_VURDERING_DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

logging.config: "classpath:logback.xml"

management:
  endpoints.web:
    base-path: /internal
    exposure.include: health

aiven-kafka:
  auto-offset-reset: earliest
  security-protocol: SSL
