name: Bygg, publish og deploy
on: push
env:
  APP: flex-juridisk-vurdering-test-backend
jobs:
  build-and-publish:
    name: Bygg, test og push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup gradle dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Lint
        run: ./gradlew ktlintCheck
      - name: Test
        run: ./gradlew test
      - name: Bygg
        run: ./gradlew bootJar
      - name: docker-build-push
        if: github.ref_name == 'master' || startsWith(github.ref_name, 'dev-')
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: flex
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  nais-deploy:
    needs: build-and-publish
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@dev-only
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
      app: ${{ inputs.app }}
      dev-only: true
    secrets: inherit
